#!/usr/bin/env node
;
var Batman, Commands, cli, noCommandGiven, oldFatal;
cli = require('./cli');
Batman = require('../lib/batman.js');
Commands = ['server', 'generate'];
cli.disable('help');
oldFatal = cli.fatal;
noCommandGiven = false;
cli.fatal = function(str) {
  if (str.match('command is required')) {
    noCommandGiven = true;
    cli.enable('help').parse(null, Commands);
    return process.exit();
  } else {
    return oldFatal(str);
  }
};
cli.parse(null, Commands);
cli.fatal = oldFatal;
cli.enable('help');
cli.setArgv(process.argv);
switch (cli.command) {
  case 'server':
    require('./server');
    break;
  case 'generate':
    require('./generator');
}